"""empty message

Revision ID: 83277e5e8a1d
Revises: 
Create Date: 2023-02-12 16:16:04.210124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83277e5e8a1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_of_entry', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog') # DROP table blog;
    # ### end Alembic commands ###
